apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: function-zen-quotes
spec:
  version: "v2.0.0"
  image: "openfunctiondev/zen-quotes-go-func:v1"
  imageCredentials:
    name: push-secret
  build:
    builder: openfunction/builder-go:latest
    env:
      FUNC_NAME: "ZenQuotes"
      FUNC_CLEAR_SOURCE: "true"
      # # Use FUNC_GOPROXY to set the goproxy if failed to fetch go modules
      # FUNC_GOPROXY: "https://goproxy.cn"
    srcRepo:
      url: "https://github.com/govindkailas/openfunction-samples.git"
      sourceSubPath: "functions/knative/zen-quotes-go"
      revision: "main"
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent 
    triggers:
      http:
        port: 8080
